name: Build App Android e Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller kivy[base]

      - name: Build Executable Windows
        run: |
          pyinstaller --onefile --noconsole --name PesoIdeal --icon=icon.ico --collect-all kivy main.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: PesoIdeal-Windows
          path: dist/PesoIdeal.exe

  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer and System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip install --upgrade buildozer Cython

      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: PesoIdeal-Android
          path: bin/*.apk